### PR TITLE
Removing the old password mask

### PR DESCRIPTION
**Pull request by duskpoet**

### CODE REVIEW

**Review by m-abdelwahab — APPROVED** [review]

**Comment by saurabh-git-dev** [comment]
@duskpoet Please verify this change I guess if the old mask is removed, the password will be exposed in endpoints I think. Because there is no other mask.

**Comment by duskpoet** [comment]
I've verified this in the test app.
@saurabh-git-dev, why do you think it will be exposed? My understanding is that the mask will be applied to whole logs

**Comment by saurabh-git-dev** [comment]
screenshot

the highlighted command dumps all API data. and it also contains the passwords in URIs.
So if you mask the password later I think this will be printed as normal text. 
As `cat branch_out` command, dumps all data.

This will be I think only for newly created branches.

I am not 100% sure if masking order is important or not.

So If you think everything is fine. Then I don't think any other issue.

**Comment by saurabh-git-dev** [comment]
Please Check my 2 latest workflow runs with customized scripts.

Latest Run - old mask removed (https://github.com/saurabh-git-dev/neon-test/actions/runs/9193850475/job/25285878634)
Second Latest Run - old mask present (https://github.com/saurabh-git-dev/neon-test/actions/runs/9193813587/job/25285754562)

**Comment by saurabh-git-dev** [comment]
I guess reorganization of code is required or can keep masks in both places.

**Comment by duskpoet** [comment]
Yea, I will it as it is for now

**Pull request closed without merging**
